title: 1505.Хаб
author:
  name: © Александр Максимов, 2022-2023
  email: maleksware@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Тренировки и дистуры по спортивному программированию. Создано с ❤️ для Гимназии 1505.
baseurl: "/hub/" # the subpath of your site, e.g. /blog
url: "https://gym1505.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed
  - jekyll-remote-theme

remote_theme: gym1505/minima

header_pages:
  - recommender.markdown
  - school-team.markdown
  - methods.markdown
  - about.markdown

minima:
  skin: dark
  
include:
  - /_img
